DROP TABLE ETHER_CONTRACT;
DROP TABLE BLOCK_CHAIN_SYNC;
DROP TABLE DEPOSIT_ETHER;
DROP TABLE WITHDRAWAL_ETHER;
DROP TABLE TRANSACTION_ETHER;


CREATE TABLE ETHER_CONTRACT
(
  CONTRACT_ADDRESS      VARCHAR(100) NOT NULL COMMENT '合约地址',
  NAME                  VARCHAR(100) NOT NULL COMMENT '名称',
  SYMBOL                VARCHAR(20) NOT NULL COMMENT '符号',
  DECIMALS              INT COMMENT NOT NULL '小数位',
  TOTALSUPPLY           DECIMAL(65,0) NOT NULL COMMENT '总发行量',
  CREATE_TIME           TIMESTAMP NULL COMMENT '创建时间',
  MODIFY_TIME           TIMESTAMP NULL COMMENT '修改时间',
  PRIMARY KEY (CONTRACT_ADDRESS)
);
ALTER TABLE ETHER_CONTRACT COMMENT 'Ether合约表';

CREATE TABLE BLOCK_CHAIN_SYNC
(
  ID                    CHAR(32) NOT NULL COMMENT 'id',
  BLOCK_TYPE            VARCHAR(20) COMMENT '区块类型(Ether、Bitcoin)',
  CURRENT_SYNC_BLOCK_NUMBER        BIGINT COMMENT '当前同步区块数',
  CREATE_TIME           TIMESTAMP NULL COMMENT '创建时间',
  MODIFY_TIME           TIMESTAMP NULL COMMENT '修改时间',
  PRIMARY KEY (ID)
);
ALTER TABLE BLOCK_CHAIN_SYNC COMMENT '区块同步表';

CREATE TABLE DEPOSIT_ETHER
(
  ID                    CHAR(32) NOT NULL COMMENT 'id',
  COIN_TYPE             VARCHAR(20) NOT NULL COMMENT '币种',
  TX_FROM               VARCHAR(100) NOT NULL COMMENT 'FORM地址',
  TX_TO                 VARCHAR(100) NOT NULL COMMENT 'TO地址',
  AMOUNT                DECIMAL(65,0) NOT NULL COMMENT '金额',
  TX_HASH               VARCHAR(100) COMMENT '交易hash',
  STATUS                VARCHAR(20) NOT NULL COMMENT '处理状态(CZWCL:充值未处理、CZCLZ:充值处理中、SUCCESS:充值成功、FAIL:充值失败)',
  TASK_STATUS           VARCHAR(20) NOT NULL COMMENT '处理状态(WCL:未处理、CLZ:处理中、SUCCESS:处理成功、FAIL:处理失败)',
  CREATE_TIME           TIMESTAMP NULL COMMENT '创建时间',
  MODIFY_TIME           TIMESTAMP NULL COMMENT '修改时间',
  PRIMARY KEY (ID)
);
ALTER TABLE DEPOSIT_ETHER COMMENT '充值ETH表';

CREATE TABLE WITHDRAWAL_ETHER
(
  ID                    CHAR(32) NOT NULL COMMENT 'id',
  WITHDRAWAL_ID         CHAR(32) NOT NULL COMMENT '取现唯一编号',
  COIN_TYPE             VARCHAR(20) NOT NULL COMMENT '币种',
  TX_FROM               VARCHAR(100) NOT NULL COMMENT 'FORM地址',
  TX_TO                 VARCHAR(100) NOT NULL COMMENT 'TO地址',
  AMOUNT                DECIMAL(65,0) NOT NULL COMMENT '金额',
  FEE                   DECIMAL(65,0) NOT NULL COMMENT '手续费',
  GAS_LIMIT             BIGINT COMMENT 'gas limit',
  GAS_USED              BIGINT COMMENT 'gas used',
  GAS_PRICE             BIGINT COMMENT 'gas price',
  TX_HASH               VARCHAR(100) COMMENT '交易hash',
  STATUS                VARCHAR(20) NOT NULL COMMENT '处理状态(CZWCL:提现未处理、CZCLZ:提现处理中、SUCCESS:提现成功、FAIL:提现失败)',
  CREATE_TIME           TIMESTAMP NULL COMMENT '创建时间',
  MODIFY_TIME           TIMESTAMP NULL COMMENT '修改时间',
  PRIMARY KEY (ID)
);
ALTER TABLE WITHDRAWAL_ETHER COMMENT '提现ETH表';

CREATE TABLE TRANSACTION_ETHER
(
  ID                    CHAR(32) NOT NULL COMMENT 'id',
  TX_HASH               VARCHAR(100) NOT NULL COMMENT '交易hash',
  BLOCK_NUMBER          BIGINT COMMENT '区块号',
  TX_FROM               VARCHAR(100) COMMENT 'FORM地址',
  TX_TO                 VARCHAR(100) COMMENT 'TO地址',
  CONTRACT_ADDRESS      VARCHAR(100) COMMENT '合约地址',
  COIN_TYPE             VARCHAR(20) COMMENT '币种',
  TX_INPUT              VARCHAR(2000) COMMENT 'input',
  TX_VALUE              DECIMAL(65,0) COMMENT '交易值',
  TX_INDEX              BIGINT COMMENT 'tx index',
  GAS_LIMIT             BIGINT COMMENT 'gas limit',
  GAS_USED              BIGINT COMMENT 'gas used',
  GAS_PRICE             BIGINT COMMENT 'gas price',
  ACTUAL_FEE            BIGINT COMMENT 'actual fee',
  NONCE                 BIGINT COMMENT 'nonce',
  TX_RECEIPT_STATUS     CHAR(1) NOT NULL COMMENT '交易状态(S:成功、F:失败、P:处理中)',
  TX_TIME               TIMESTAMP NULL COMMENT '交易时间',
  CONFIRM_BLOCK_NUMBER  INT COMMENT '确认区块数',
  TX_STATUS             VARCHAR(20) NOT NULL COMMENT '交易状态(WCL:未处理、QKQRSCLZ:区块确认数处理中、YEWQR:余额未确认、YEQRYC:余额确认异常、YX:有效、WX:无效)',
  CREATE_TIME           TIMESTAMP NULL COMMENT '创建时间',
  MODIFY_TIME           TIMESTAMP NULL COMMENT '修改时间',
  PRIMARY KEY (ID)
);
ALTER TABLE TRANSACTION_ETHER COMMENT 'ETH交易表';