DROP TABLE USER;
DROP TABLE USER_LOGIN_JNL;
DROP TABLE CIF;

CREATE TABLE USER
(
   USER_ID              CHAR(32) NOT NULL COMMENT '用户编号',
   USERNAME             VARCHAR(100) COMMENT '用户名',
   PASSWORD             VARCHAR(200) COMMENT '密码',
   PAYMENT_PASSWORD     VARCHAR(200) COMMENT '支付密码',
   PAYMENT_PASSWORD_FAIL_COUNTER    INT COMMENT '支付密码验证失败次数',
   NICK                 VARCHAR(100) COMMENT '昵称',
   MOBILE_PREFIX        VARCHAR(10) COMMENT '手机前缀',
   MOBILE               VARCHAR(11) COMMENT '手机',
   EMAIL                VARCHAR(200) COMMENT '邮箱',
   CIF_ID               CHAR(32) COMMENT '客户信息',
   USER_PICTURE         VARCHAR(200) COMMENT '用户图片',
   STATUS               VARCHAR(10) NOT NULL COMMENT '用户状态(初始化:CSH、YRZ:已认证、WRZ:未认证、SD:锁定、HMD:黑名单)',
   LOCK_EXPIRE_TIME		  TIMESTAMP NULL COMMENT '账户锁定失效时间',
   CREATE_CHANNEL       CHAR(2) COMMENT '创建渠道(00:系统注册)',
   LOGIN_TOKEN          CHAR(32) COMMENT '登录TOKEN',
   LOGIN_TOKEN_EXPIRAT_TIME TIMESTAMP NULL COMMENT '登录TOKEN失效时间',
   LAST_LOGIN_TIME      TIMESTAMP NULL COMMENT '最后登录时间',
   LAST_LOGIN_IP        VARCHAR(40) NOT NULL COMMENT '最后登录IP',
   LOGIN_DEVICE_CODE    VARCHAR(60) COMMENT '登录设备编号',
   LAST_LOGIN_DEVICE    VARCHAR(40) COMMENT '最后登录设备类型',
   LAST_LOGIN_LOCALE    VARCHAR(40) COMMENT '最后登录时语言环境',
   FAIL_LOGIN_COUNTER   INT COMMENT '登录失败次数',
   CREATE_TIME          TIMESTAMP NULL COMMENT '创建时间',
   MODIFY_TIME          TIMESTAMP NULL COMMENT '修改时间',
   PRIMARY KEY (USER_ID),
   UNIQUE KEY UK_USERNAME(USERNAME)
);
ALTER TABLE USER COMMENT '用户表';

CREATE TABLE USER_LOGIN_JNL
(
   ID                   CHAR(32) NOT NULL COMMENT '编号',
   USERNAME             VARCHAR(100) COMMENT '用户名',
   LOGIN_IP             VARCHAR(40) COMMENT '登录IP',
   LOGIN_DEVICE_CODE    VARCHAR(60) COMMENT '登录设备编号',
   LOGIN_TYPE           CHAR(2) COMMENT '登录类型(00:邮箱验证码登录、01:TOKEN登录)',
   LOGIN_STATUS         CHAR(1) COMMENT '登录状态(S:成功、F:失败)',
   CREATE_TIME          TIMESTAMP NULL COMMENT '创建时间',
   MODIFY_TIME          TIMESTAMP NULL COMMENT '修改时间',
   PRIMARY KEY (ID)
);
ALTER TABLE USER_LOGIN_JNL COMMENT '用户登录日志表';

CREATE TABLE CIF
(
   ID                   CHAR(32) NOT NULL COMMENT 'ID',
   CIF_NAME             VARCHAR(100) COMMENT '姓名',
   SEX                  CHAR(1) COMMENT '性别(M:男、F:女)',
   BIRTHDAY             TIMESTAMP NULL COMMENT '出生日期',
   ID_TYPE              CHAR(2) COMMENT '证件类型(00:身份证)',
   ID_NUM               VARCHAR(200) COMMENT '证件号码',
   HALF_PHOTO           VARCHAR(200) COMMENT '半身照片',
   IDENTITY_PHOTOS_FORNT VARCHAR(200) COMMENT '身份正面照',
   IDENTITY_PHOTOS_REAR VARCHAR(200) COMMENT '身份正反面',
   IDENTITY_PHOTOS_HOLD VARCHAR(200) COMMENT '手持身份证',
   CREATE_TIME          TIMESTAMP NULL COMMENT '创建时间',
   MODIFY_TIME          TIMESTAMP NULL COMMENT '修改时间',
   PRIMARY KEY (ID)
);
ALTER TABLE CIF COMMENT '个人信息';