CREATE DATABASE blockchain_key CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI;

CREATE USER 'blockchain_key'@'%' IDENTIFIED BY 'jfYYWE!*&NCs437923';

GRANT ALL PRIVILEGES ON blockchain_key.* TO 'blockchain_key'@'%';