DROP TABLE MNEMONIC;
DROP TABLE EXTENDED_KEY;
DROP TABLE SECRET_KEY;

CREATE TABLE MNEMONIC
(
  ID                    CHAR(32) NOT NULL COMMENT 'id',
  FILE_PATH             VARCHAR(5000) COMMENT '文件路径',
  CREATE_TIME           TIMESTAMP NULL COMMENT '创建时间',
  MODIFY_TIME           TIMESTAMP NULL COMMENT '修改时间',
  PRIMARY KEY (ID)
);
ALTER TABLE MNEMONIC COMMENT '助记词表';

CREATE TABLE EXTENDED_KEY
(
  ID                    CHAR(32) NOT NULL COMMENT 'id',
  MNEMONIC_ID           CHAR(32) NOT NULL COMMENT '助记词id',
  EXTENDED_KEY_PATH     VARCHAR(200) COMMENT '扩展密钥路径',
  FILE_PATH             VARCHAR(5000) COMMENT '文件路径',
  CURRENT_INDEX_NUMBER  INT COMMENT '当索引号',
  CREATE_TIME           TIMESTAMP NULL COMMENT '创建时间',
  MODIFY_TIME           TIMESTAMP NULL COMMENT '修改时间',
  PRIMARY KEY (ID)
);
ALTER TABLE EXTENDED_KEY COMMENT '扩展密钥表';

CREATE TABLE SECRET_KEY
(
  ID                    CHAR(32) NOT NULL COMMENT 'id',
  EXTENDED_KEY_ID       CHAR(32) NOT NULL COMMENT '扩展密钥id',
  ADDRESS               VARCHAR(100) COMMENT '地址',
  KEY_PATH              VARCHAR(200) COMMENT 'key路径',
  FILE_PATH             VARCHAR(5000) COMMENT '文件路径',
  CREATE_TIME           TIMESTAMP NULL COMMENT '创建时间',
  MODIFY_TIME           TIMESTAMP NULL COMMENT '修改时间',
  PRIMARY KEY (ID)
);
ALTER TABLE SECRET_KEY COMMENT '密钥表';