#!/bin/sh

JAVA_OPTIONS="${JAVA_OPTIONS} -Dfile.encoding=UTF-8"
JAVA_VM="-server"
MEM_ARGS="-Xms2048m -Xmx2048m"
APP_HOME=/home/ole/ole-wallet-server

nohup java ${JAVA_VM} ${MEM_ARGS} ${JAVA_OPTIONS} -jar $APP_HOME/ole-wallet-server.jar --spring.config.name=application-test 1>>$APP_HOME/ole-wallet-server.out 2>&1 &