#!/bin/sh

JAVA_OPTIONS="${JAVA_OPTIONS} -Dfile.encoding=UTF-8"
JAVA_VM="-server -javaagent:/Users/Joly/Work/Joly/Maven/Repository/org/springframework/spring-instrument/4.3.8.RELEASE/spring-instrument-4.3.8.RELEASE.jar"
MEM_ARGS="-Xms4096m -Xmx4096m"
APP_HOME=/Users/Joly/Work/Joly/project/bcoin-exchange/ether-observe/target

nohup java ${JAVA_VM} ${MEM_ARGS} ${JAVA_OPTIONS} -jar $APP_HOME/ether-observe.jar --spring.config.name=application 1>>$APP_HOME/ether-observe.out 2>&1 &