#!/bin/sh

JAVA_OPTIONS="${JAVA_OPTIONS} -Dfile.encoding=UTF-8"
JAVA_VM="-server"
MEM_ARGS="-Xms2048m -Xmx2048m"
APP_HOME=/home/blockchain/ether-observe

nohup java ${JAVA_VM} ${MEM_ARGS} ${JAVA_OPTIONS} -jar $APP_HOME/ether-observe.jar --spring.config.name=application-prod 1>>$APP_HOME/ether-observe.out 2>&1 &