DROP TABLE MNEMONIC;
DROP TABLE EXTENDED_KEY;
DROP TABLE SECRET_KEY;
DROP TABLE BLOCK_CHAIN_SYNC;
DROP TABLE SYS_PRM;
DROP TABLE BIT_COIN;
DROP TABLE ACCOUNT;
DROP TABLE ACCOUNT_JNL;
DROP TABLE ADDRESS_LISTENER;
DROP TABLE TRANSACTION_NOTICE;

CREATE TABLE MNEMONIC
(
   ID                   CHAR(32) NOT NULL COMMENT 'id',
   NAME                 VARCHAR(200) COMMENT '别名',
   PASSWORD             VARCHAR(500) NOT NULL COMMENT '密码',
   CREATE_TIME          TIMESTAMP NULL COMMENT '创建时间',
   MODIFY_TIME          TIMESTAMP NULL COMMENT '修改时间',
   PRIMARY KEY (ID)
);
ALTER TABLE MNEMONIC COMMENT '助记词表';

CREATE TABLE EXTENDED_KEY
(
   ID                   CHAR(32) NOT NULL COMMENT 'id',
   MNEMONIC_ID          CHAR(32) NOT NULL COMMENT '助记词id',
   EXTENDED_KEY_PATH    VARCHAR(200) COMMENT '扩展密钥路径',
   PASSWORD             VARCHAR(500) NOT NULL COMMENT '密码',
   CREATE_TIME          TIMESTAMP NULL COMMENT '创建时间',
   MODIFY_TIME          TIMESTAMP NULL COMMENT '修改时间',
   PRIMARY KEY (ID)
);
ALTER TABLE EXTENDED_KEY COMMENT '扩展密钥表';

CREATE TABLE SECRET_KEY
(
  ID                    CHAR(32) NOT NULL COMMENT 'id',
  ADDRESS               VARCHAR(100) COMMENT '地址',
  EXTENDED_KEY_ID       CHAR(32) NOT NULL COMMENT '扩展密钥id',
  KEY_PATH              VARCHAR(200) COMMENT 'key路径',
  PASSWORD              VARCHAR(500) NOT NULL COMMENT '密码',
  CREATE_TIME           TIMESTAMP NULL COMMENT '创建时间',
  MODIFY_TIME           TIMESTAMP NULL COMMENT '修改时间',
  PRIMARY KEY (ID)
);
ALTER TABLE SECRET_KEY COMMENT '密钥表';

CREATE TABLE BLOCK_CHAIN_SYNC
(
  ID                    CHAR(32) NOT NULL COMMENT 'id',
  BLOCK_TYPE            VARCHAR(20) COMMENT '区块类型(Ether、Bitcoin)',
  CURRENT_SYNC_BLOCK_NUMBER        BIGINT COMMENT '当前同步区块数',
  CREATE_TIME           TIMESTAMP NULL COMMENT '创建时间',
  MODIFY_TIME           TIMESTAMP NULL COMMENT '修改时间',
  PRIMARY KEY (ID)
);
ALTER TABLE BLOCK_CHAIN_SYNC COMMENT '区块同步表';

CREATE TABLE SYS_PRM
(
  ID                    CHAR(32) NOT NULL COMMENT 'id',
  PRM_NAME              VARCHAR(100) NOT NULL COMMENT '参数名称',
  PRM_VALUE             VARCHAR(200) NOT NULL COMMENT '参数值',
  PRM_DESC              VARCHAR(200) COMMENT '参数描述',
  PRM_STATUS            CHAR(2) NOT NULL COMMENT '参数状态(01:有效、02:失效)',
  CREATE_TIME           TIMESTAMP NULL COMMENT '创建时间',
  MODIFY_TIME           TIMESTAMP NULL COMMENT '修改时间',
  PRIMARY KEY (ID)
);
ALTER TABLE SYS_PRM COMMENT '系统参数表';

CREATE TABLE BIT_COIN
(
  ID                    CHAR(32) NOT NULL COMMENT 'id',
  BLOCK_TYPE            VARCHAR(20) COMMENT '区块类型(Bitcoin、Ether)',
  COIN_TYPE             VARCHAR(20) COMMENT '币种名称',
  BIP44_COIN_TYPE       VARCHAR(20) COMMENT 'bip44币种',
  DECIMALS              INT COMMENT '小数位',
  CREATE_TIME           TIMESTAMP NULL COMMENT '创建时间',
  MODIFY_TIME           TIMESTAMP NULL COMMENT '修改时间',
  PRIMARY KEY (ID)
);
ALTER TABLE BIT_COIN COMMENT '币种表';

CREATE TABLE ACCOUNT
(
  ID                    CHAR(32) NOT NULL COMMENT 'id',
  ADDRESS               VARCHAR(100) NOT NULL COMMENT '地址',
  COIN_TYPE             VARCHAR(20) NOT NULL COMMENT '币种',
  TOTAL_IN              DECIMAL(65,0) NOT NULL COMMENT '入账总额',
  TOTAL_OUT             DECIMAL(65,0) NOT NULL COMMENT '出账总额',
  BALANCE               DECIMAL(65,0) NOT NULL COMMENT '余额',
  FROZEN_AMOUNT         DECIMAL(65,0) NOT NULL COMMENT '冻结金额',
  STATUS                VARCHAR(10) NOT NULL COMMENT '账户状态(NORMAL:正常、LOCK:锁定)',
  CREATE_TIME           TIMESTAMP NULL COMMENT '创建时间',
  MODIFY_TIME           TIMESTAMP NULL COMMENT '修改时间',
  PRIMARY KEY (ID)
);
ALTER TABLE ACCOUNT COMMENT '账户表';

CREATE TABLE ACCOUNT_JNL
(
  ID                    CHAR(32) NOT NULL COMMENT 'id',
  ACCOUNT_FROM          VARCHAR(100) COMMENT 'from地址',
  ACCOUNT_TO            VARCHAR(100) COMMENT 'to地址',
  COIN_TYPE             VARCHAR(20) COMMENT '币种',
  BALANCE               DECIMAL(65,0) NOT NULL COMMENT '金额',
  TYPE                  CHAR(2) COMMENT '类型(00:转入、01:转出、10:冻结、11:解冻)',
  TX_ID                 VARCHAR(32) COMMENT '交易id',
  TRANS_TIME            TIMESTAMP NULL COMMENT '交易时间',
  CREATE_TIME           TIMESTAMP NULL COMMENT '创建时间',
  MODIFY_TIME           TIMESTAMP NULL COMMENT '修改时间',
  PRIMARY KEY (ID)
);
ALTER TABLE ACCOUNT_JNL COMMENT '账户流水表';

CREATE TABLE ADDRESS_LISTENER
(
  ADDRESS               VARCHAR(100) COMMENT '地址',
  BLOCK_TYPE            VARCHAR(20) COMMENT '区块类型(Bitcoin、Ether)',
  CREATE_TIME           TIMESTAMP NULL COMMENT '创建时间',
  MODIFY_TIME           TIMESTAMP NULL COMMENT '修改时间',
  PRIMARY KEY (ADDRESS)
);
ALTER TABLE ADDRESS_LISTENER COMMENT '地址监听表';

CREATE TABLE TRANSACTION_NOTICE
(
  ID                    CHAR(32) NOT NULL COMMENT 'id',
  BLOCK_TYPE            VARCHAR(20) COMMENT '区块类型(Bitcoin、Ether)',
  NOTICE_ADDRESS        VARCHAR(2000) NOT NULL COMMENT '通知地址',
  NOTICE_TYPE           VARCHAR(50) NOT NULL COMMENT '通知类型(DEPOSIT:充值、WITHDRAWAL:取现)',
  CREATE_TIME           TIMESTAMP NULL COMMENT '创建时间',
  MODIFY_TIME           TIMESTAMP NULL COMMENT '修改时间',
  PRIMARY KEY (ID)
);
ALTER TABLE TRANSACTION_NOTICE COMMENT '交易通知表';